version: "3"
services:

  nexus:
    container_name: nexus_repository
    image: sonatype/nexus3:3.63.0
    volumes:
      - nexus_data:/nexus-data
    ports:
      - "8081:8081"
      - "8085:8085"
    restart: unless-stopped
    environment:
      - INSTALL4J_ADD_VM_PARAMS="-Xms32m -Xmx128m -XX:MaxDirectMemorySize=256m -Djava.util.prefs.userRoot=/nexus"

volumes:
  nexus_data: