version: "3.3"

services:

   gitlab:
      image: "gitlab/gitlab-ce:latest"
      networks:
         - principal
      ports:
         - "2222:22"
      volumes:
        - "gitlab_config:/etc/gitlab"
        - "gitlab_data:/var/opt/gitlab"
      deploy:
         restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
         labels:
            - "traefik.frontend.rule=Host:gitlab.labary.local"
            - "traefik.enable=true"
            - "traefik.docker.network=principal"
            - "traefik.port=80"
            - "traefik.frontend.entryPoints=http"
            - "traefik.backend.loadbalancer.sticky=true"        

   jenkins:
      image: "johnnysilva110/jenkins-docker:1.0"
      networks:
         - principal
      volumes:
        - "jenkins_home:/var/jenkins_home"
        - "/var/run/docker.sock:/var/run/docker.sock"
      deploy:
         replicas: 3
         placement:
            constraints:
               - node.role == manager
         restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s 
         labels:
            - "traefik.frontend.rule=Host:jenkins.labary.local"
            - "traefik.enable=true"
            - "traefik.docker.network=principal"
            - "traefik.port=8080"
            - "traefik.frontend.entryPoints=http"
            - "traefik.backend.loadbalancer.sticky=true"                  

networks:
   principal:
      external: true
      driver: overlay

volumes:
   gitlab_config:
      driver_opts:
         type: "nfs"
         o: "addr=192.168.1.34,nolock,soft,rw"
         device: ":/mnt/dir_docker_volume/gitlab_config"
   gitlab_data:
      driver_opts:
         type: "nfs"
         o: "addr=192.168.1.34,nolock,soft,rw"
         device: ":/mnt/dir_docker_volume/gitlab_data"
   jenkins_home:
      driver_opts:
         type: "nfs"
         o: "addr=192.168.1.34,nolock,soft,rw"
         device: ":/mnt/dir_docker_volume/jenkins_home"