version: "3.3"

services:

   gitlab:
      image: "store/gitlab/gitlab-ee:11.10.4-ee.0"
      networks:
         - principal
      ports:
         - "2222:22"
      volumes:
         - "gitlab_config:/etc/gitlab"
         - "gitlab_data:/var/opt/gitlab"
      deploy:
         #restart_policy:
         #   condition: on-failure
         #   delay: 5s
         #   max_attempts: 3
         #   window: 120s
         labels:
            - "traefik.frontend.rule=Host:gitlab.labary.local"
            - "traefik.enable=true"
            - "traefik.docker.network=principal"
            - "traefik.port=80"
            - "traefik.frontend.entryPoints=http"
            - "traefik.backend.loadbalancer.stickiness=true"

networks:
   principal:
      external: true
      driver: overlay

volumes:
   gitlab_config:
      driver_opts:
         type: "nfs"
         o: "addr=192.168.1.34,nolock,soft,rw"
         device: ":/mnt/dir_docker_volume/gitlab_config"
   gitlab_data:
      driver_opts:
         type: "nfs"
         o: "addr=192.168.1.34,nolock,soft,rw"
         device: ":/mnt/dir_docker_volume/gitlab_data"