version: "3.3"

services:

   jenkins_agent:
      image: "jenkins/slave:alpine"
      workdir: "/home/jenkins/agent"
      command: --"java -jar /usr/share/jenkins/agent.jar" 
      environment:
         JENKINS_URL: http://jenkins.labary.local/
         JENKINS_AGENT_WORKDIR: /home/jenkins/agent
      networks:
         - jenkins_agent
      volumes:
         - "/var/run/docker.sock:/var/run/docker.sock:ro"
         - "jenkins_agent:/var/jenkins/agent"
      deploy:
         mode: global
         placement:
            constraints:
               - node.role == manager
         restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s 

networks:
   jenkins_agent:
      external: true
      driver: overlay

volumes:
   jenkins_agent:
      driver_opts:
         type: "nfs"
         o: "addr=192.168.1.34,nolock,soft,rw"
         device: ":/mnt/dir_docker_volume/jenkins_agent"