version: '3.3'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.portainer.agent:9001 --tlsskipverify
    depends_on:
      - agent
    networks:
      - principal
      - portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      restart_policy: 
         condition: on-failure
      labels:
        - "traefik.frontend.rule=Host:portainer.labary.local"
        - "traefik.enable=true"
        - "traefik.docker.network=principal"
        - "traefik.port=9000"
        - "traefik.frontend.entryPoints=http"
        - "traefik.backend.loadbalancer.stickiness=true"

networks:
  principal:
    external: true
  portainer_agent:
    driver: overlay
    external: true
    attachable: true

volumes:
   portainer_data:
      driver_opts:
         type: "nfs"
         o: "addr=192.168.1.34,nolock,soft,rw"
         device: ":/mnt/dir_docker_volume/portainer_data"