version: "3.8"

services:

   traefik:
      image: traefik:v1.7.24-alpine
      #command: #--api \
               #--docker \
               #--docker.swarmMode \
               #--docker.watch \
               #--logLevel=DEBUG \
               #--docker.domain=labary.local 
               #--docker.endpoint=tcp://127.0.0.1:2375
      networks:
         - net-proxy
      dns: 1.1.1.1
      ports:
         - target: 80
           published: 80
           protocol: tcp
           mode: host
         - target: 8080
           published: 8080
           protocol: tcp
           mode: host
         - target: 443
           published: 443
           protocol: tcp
           mode: host
      volumes:
         - "/var/run/docker.sock:/var/run/docker.sock:ro"
         - "/etc/localtime:/etc/localtime:ro"
         - "traefik_certs:/certs"
         - "traefik_config:/etc/traefik/traefik.toml"
      deploy:
         mode: global
         placement:
            constraints: [node.role == manager]
         resources:
           limits:
             #cpus: '2.50'
             memory: 100M
         update_config:
            parallelism: 1
            delay: 10s
         restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 1
            window: 120s
      labels:
         - "traefik.frontend.rule=Host:traefik.labary.local"
         - "traefik.port=8080"
         - "traefik.backend.loadbalancer.method=drr"
         - "traefik.enable=true"

networks:
   net-proxy:
      driver: overlay
      external: true

volumes:
   traefik_certs:
      driver_opts:
         type: "none"
         o: "bind"
         device: "/mnt/gluster_docker/volumes/traefik_certs/_data"
   traefik_config:
      driver_opts:
         type: "none"
         o: "bind"
         device: "/mnt/gluster_docker/volumes/traefik_config/_data/traefik.toml"