version: "3.3"

services:

   reverse_proxy:
      image: traefik:1.7
      command: --api \
               --docker \
               --docker.swarmMode \
               --docker.watch \
               --logLevel=DEBUG \
               --"entrypoints=Name:http Address::80 Redirect.EntryPoint:https" \
               --"entrypoints=Name:https Address::443 TLS" \
               --defaultentrypoints=http,https \
               --acme \
               --acme.storage=/etc/traefik/acme/acme.json \
               --acme.entryPoint=https \
               --acme.httpChallenge.entryPoint=http \
               --acme.onHostRule=true \
               --acme.email=johnnysilva110@hotmail.com
      networks:
         - principal
      ports:
         - target: 80
           published: 80
           protocol: tcp
           mode: host
         - target: 8080
           published: 8080
           protocol: tcp
           mode: host
         - target: 443
           published: 443
           protocol: tcp
           mode: host
      volumes:
         - "/var/run/docker.sock:/var/run/docker.sock"
         - "traefik_cert:/etc/traefik/acme/acme.json"
      deploy:
         mode: global
         placement:
            constraints:
               - node.role == manager

networks:
   principal:
      external: true
      driver: overlay

volumes:
   traefik_cert:
      driver_opts:
         type: "nfs"
         o: "addr=192.168.1.34,nolock,soft,rw"
         device: ":/mnt/dir_docker_volume/traefik_cert"