version: "3.7"

services:

   reverse_proxy:
      image: traefik:1.7
      command: --api --docker --docker.swarmMode --docker.domain=labary.local --docker.watch --logLevel=DEBUG
      networks:
         - principal
      ports:
         - target: 80
         published: 80
         protocol: tcp
         mode: host
         - target: 8080
         published: 8080
         protocol: tcp
         mode: host
         - target: 443
         published: 443
         protocol: tcp
         mode: host
      volumes:
         - "/var/run/docker.sock:/var/run/docker.sock" 
      deploy:
         mode: global
         placement:
            constraints:
               - node.role == manager

networks:
   principal:
      external: true
      driver: overlay