version: "2.4"
services:

  jenkins:
    image: jenkins/jenkins:2.387.1-lts-alpine
    ports:
      - "8088:8080"
    restart: always
    mem_limit: 512m 
    #cpus: 1.50
    volumes:
      - /DOCKER_VOLUMES/jenkins_data:/var/jenkins_home:rw
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JAVA_OPTS="-Xmx512m"