version: '3.3'

services:
  
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 9001
      LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - interna
      - agent_portainer
    deploy:
      mode: global
      placement:
        constraints: 
          - "node.platform.os == linux"

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - interna
      - agent_portainer
    ports:
      - "9000:9000"
    deploy:
      labels:
      - "traefik.front.rule=Host:portainer.opovo.local"
      - "traefik.backend=portainer"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.docker.network=interna"
      - "trefik.backend.loadbalancer.sticky=true"
      placement:
        constraints: 
          - node.role == manager

networks:
  interna:
    external: true
    attachable: true
  agent_portainer:
    driver: overlay
    attachable: true
    external: true

volumes:
    portainer_data:
      driver_opts:
         type: "nfs"
         device: :/dir_persistence_volume_docker/portainer_data/
         o: addr=192.168.30.103,rw,nolock,soft
