version: "3.3"

services:

   traefik:
      image: traefik:v1.7.24-alpine
      networks:
         - net-proxy
      dns:
         - 192.168.0.200
         - 192.168.0.202
      dns_search: opovo.local
      ports:
         - target: 80
           published: 80
           protocol: tcp
           mode: host
         - target: 8080
           published: 8080
           protocol: tcp
           mode: host
         - target: 443
           published: 443
           protocol: tcp
           mode: host
      volumes:
         - "/var/run/docker.sock:/var/run/docker.sock:ro"
         - "/etc/localtime:/etc/localtime:ro"
         - "traefik_certs:/certs"
         - "/mnt/gluster_docker/volumes/traefik_config/_data/traefik.toml:/etc/traefik/traefik.toml"
      deploy:
         mode: global
         placement:
            constraints: [node.role == manager]
         resources:
           limits:
             #cpus: '2.50'
             memory: 100M
         update_config:
            parallelism: 1
            delay: 10s
         restart_policy:
            condition: on-failure
      labels:
         - "traefik.frontend.rule=Host:traefik.opovo.local"
         - "traefik.port=8080"
         - "traefik.backend.loadbalancer.method=drr"
         - "traefik.enable=true"

networks:
   net-proxy:
      driver: overlay
      external: true

volumes:
   traefik_certs:
      driver_opts:
         type: "none"
         o: "bind"
         device: "/mnt/gluster_docker/volumes/traefik_certs/_data"